from colortools.util import DominantColorAlgorithm
from colortools.heuristics import NColorsHeuristic


DEFAULT_BAR_HEIGHT = 500
DEFAULT_BAR_WIDTH = 100
DEFAULT_COLLAGE_DIR = "collages"
DEFAULT_COLLAGE_SPACING = 10
DEFAULT_DOMINANT_COLOR_ALGORITHM = DominantColorAlgorithm.KMEANS
DEFAULT_DOMINANT_COLOR_CHIP_BORDER = 40
DEFAULT_DOMINANT_COLOR_CHIP_GAP = 10
DEFAULT_DOMINANT_COLOR_CHIP_SIZE = 80
DEFAULT_DOMINANT_COLOR_DIR = "dominant_colors"
DEFAULT_N_COLORS = None
DEFAULT_N_COLORS_HEURISTIC = NColorsHeuristic.DEFAULT
DEFAULT_OUTPUT_DIR = "output"
DEFAULT_RESIZE_LONG_AXIS = 400
DEFAULT_SORTED_DIR = "sorted"
DEFAULT_SPECTRUM_DIR = "spectrums"
