from colortools.heuristics import NColorsHeuristic
from colortools.sort import SortMethod
from colortools.util import DominantColorAlgorithm

DEFAULT_BAR_HEIGHT = 500
DEFAULT_BAR_WIDTH = 100
DEFAULT_COLLAGE_DIR = "collages"
DEFAULT_COLLAGE_SPACING = 10
DEFAULT_COLLAGE_WIDTH = "sqrt"
DEFAULT_DOMINANT_COLOR_ALGORITHM = DominantColorAlgorithm.KMEANS
DEFAULT_DOMINANT_COLOR_CHIP_BORDER = 40
DEFAULT_DOMINANT_COLOR_CHIP_GAP = 10
DEFAULT_DOMINANT_COLOR_CHIP_SIZE = 80
DEFAULT_DOMINANT_COLOR_DIR = "dominant_colors"
DEFAULT_N_COLORS = None
DEFAULT_N_COLORS_HEURISTIC = NColorsHeuristic.AUTO_N_BINNED_WITH_THRESHOLD
DEFAULT_N_COLORS_MIN = 1
DEFAULT_OUTPUT_DIR = "output"
DEFAULT_RESIZE_LONG_AXIS = 400
DEFAULT_SORT_METHOD = SortMethod.COLOR
DEFAULT_SORTED_DIR = "sorted"
DEFAULT_SPECTRUM_DIR = "spectrums"
